config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "books#index"
  resources :books 
    resources :users, only: :show
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

    belongs_to :user
    has_one    :orders
    has_one_attached :image
  
    extend ActiveHash::Associations::ActiveRecordExtensions
    belongs_to :publishing_company
    belongs_to :category
  
    with_options presence: true do
    validates :title
    validates :author
    validates :summary
    validates :image
  end
  
  validates :publishing_company_id, numericality: { other_than: 0 }
  validates :category_id, numericality: { other_than: 0 }
  
end

app/models/category.rb
class Category < ActiveHash::Base
  
  self.data = [
    { id: 0, name: '---' },
    { id: 1, name: '文学・小説' },
    { id: 2, name: '社会・ビジネス' },
    { id: 3, name: '旅行・地図' },
    { id: 4, name: '趣味' },
    { id: 5, name: '実用・教育' },
    { id: 6, name: 'アート・教養・エンタメ' },
    { id: 7, name: '事典・図鑑・語学・辞書' },
    { id: 8, name: 'こども' },
    { id: 9, name: 'その他' }
  ]

  include ActiveHash::Associations
  has_many :books
end

app/models/publishing_company.rb
class PublishingCompany < ActiveHash::Base
  
  self.data = [
    { id: 0, name: '---' },
    { id: 1, name: '講談社' },
    { id: 2, name: '集英社' },
    { id: 3, name: 'KADOKAWA' },
    { id: 4, name: '小学館' },
    { id: 5, name: 'ゼンリン' },
    { id: 6, name: '日経BP' },
    { id: 7, name: '学研HD' },
    { id: 8, name: 'ベネッセHD' },
    { id: 9, name: '文藝春秋' },
    { id: 10, name: 'サイネックス' },
    { id: 11, name: 'インプレスHD' },
    { id: 12, name: 'ダイヤモンド社' },
    { id: 13, name: '文溪堂' },
    { id: 14, name: 'キャリアデザインセンター' },
    { id: 15, name: '東洋経済新報社' },
    { id: 16, name: '朝日新聞出版' },
    { id: 17, name: 'ぱど' },
    { id: 18, name: '昭文社HD' },
    { id: 19, name: 'SEHD・アンド・インキュベー' },
    { id: 20, name: 'アルファポリス' },
    { id: 21, name: 'その他' }
  ]

  include ActiveHash::Associations
  has_many :books

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books

  with_options presence: true do
  validates :nickname
  # validates :first_name
  # validates :last_name
end

validates :email, uniqueness: true

PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
validates_format_of :password, with: PASSWORD_REGEX, message: '6文字以上半角英数字を含めて設定してください'
validates :password, length: { minimum: 6 }

# with_options format: { with: /\A[ぁ-んァ-ヶ一-龥々]+\z/, message: '全角（漢字・ひらがな・カタカナ）で入力してください' } do
#   validates :first_name
#   validates :last_name
# end

# with_options format: { with: /\A[\p{katakana}ー－&&[^ -~｡-ﾟ]]+\z/, message: '全角カタカナを入力して下さい' } do
#   validates :first_name_kana
#   validates :last_name_kana
# end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys:
    [:nickname])
  end

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV['BASIC_AUTH_USER'] && password == ENV['BASIC_AUTH_PASSWORD']
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_book, only: [:edit, :show, :update, :destroy]
  before_action :redirect_root, only: [:edit, :update, :destroy]
 
  def index
    @books = Book.order('created_at DESC')
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
    redirect_to root_path
    else
    render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @book.update(book_params)
       redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    @book.destroy
    redirect_to root_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :author, :publishing_company_id, :category_id, :summary, :output, :image).merge(user_id: current_user.id)
  end

  def redirect_root
    redirect_to root_path unless @book.user_id = current_user.id
  end

  def set_book
    @book = Book.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 
  def show
    @user = User.find(params[:id])
    # @nickname = user.nickname
    # @books = user.books
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_book.html.erb
<div class="item-show">
  <div class="item-box">

    <div class="item-img-content">
      <%= link_to image_tag(book.image, class: :card__img ), book_path(book.id) , method: :get%>
    </div>

    <table class="detail-table">
      <tbody>

        <tr>
          <th class="detail-item">タイトル</th>
          <td class="detail-value"><%= book.title %></td>
        </tr>

        <tr>
          <th class="detail-item">レビュー</th>
          <td class="detail-value"><%= book.summary %></td>
        </tr>

        <tr>
          <th class="detail-item">カテゴリー</th>
          <td class="detail-value"><%= book.category.name %></td>
        </tr>

        <tr>
          <th class="detail-item">出版社</th>
          <td class="detail-value"><%= book.publishing_company.name %></td>
        </tr>

        <tr>
          <th class="detail-item">得られた学び</th>
          <td class="detail-value"><%= book.output %></td>
        </tr>
      </tbody>
    </table>

  </div>
</div>

app/views/books/edit.html.erb
<%# cssは商品出品のものを併用しています。
app/assets/stylesheets/items/new.css %>

<div class="items-sell-contents">
  <%# <header class="items-sell-header">
    <%= link_to image_tag('book-logo01.png' , size: '185x50'), "/" %>
      <%= link_to image_tag('book-logo-color03.png' , size: '160x120'),root_path %>
  </header>
  <div class="items-sell-main">
    <h2 class="items-sell-title">編集してください</h2>
    <%= form_with model:@book, local: true do |f| %>

    <%= render 'shared/error_messages', model: f.object %>

    <%# 出品画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        出品画像
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"item-image" %>
      </div>
    </div>
    <%# /出品画像 %>
    <%# 商品名と商品説明 %>
    <div class="new-items">
      <div class="weight-bold-text">
        <%# <span class="indispensable">必須</span> %>
      </div>
      <%= f.text_area :title, class:"items-text", id:"item-name", placeholder:"本のタイトル", maxlength:"40" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          <%# <span class="indispensable">必須</span> %>
        </div>
        <%= f.text_area :author, class:"items-text", id:"item-info", placeholder:"著者" ,rows:"7" ,maxlength:"1000" %>
      </div>
    </div>
    <%# /商品名と商品説明 %>

    <div class="items-explain">
        <div class="weight-bold-text">
         <%# 要約 %>
          <%# <span class="indispensable">必須</span> %>
        </div>
        <%= f.text_area :summary, class:"items-text", id:"item-info", placeholder:"本の要約" ,rows:"7" ,maxlength:"1000" %>
      </div>
    </div>

    <%# 商品の詳細 %>
    <div class="items-detail">
      <div class="weight-bold-text"></div>
      <div class="form">
        <div class="weight-bold-text">
          カテゴリー
          <%# <span class="indispensable">必須</span> %>
        </div>
        <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
        <div class="weight-bold-text">
          出版社
          <%# <span class="indispensable">必須</span> %>
        </div>
        <%= f.collection_select(:publishing_company_id, PublishingCompany.all, :id, :name, {}, {class:"select-box", id:"item-sales-status"}) %>
      </div>
    </div>
      <div class="items-explain">
        <div class="weight-bold-text">
          <%# 得られる学び %>
          <%# <span class="indispensable">任意</span> %>
        </div>
        <%= f.text_area :output, class:"items-text", id:"item-info", placeholder:"得られた学び" ,rows:"7" ,maxlength:"1000" %>
    </div>

    <%# /商品の詳細 %>

    <%# 配送について %>
    <%# <div class="items-detail">
      <div class="weight-bold-text question-text">
        <span>配送について</span>
        <a class="question" href="#">?</a>
      </div>
      <div class="form">
        <div class="weight-bold-text">
          配送料の負担
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:shipping_charge_id, ShippingCharge.all, :id, :name, {}, {class:"select-box", id:"item-shipping-fee-status"}) %>
        <%# <div class="weight-bold-text">
          発送元の地域
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:city_id, City.all, :id, :name, {}, {class:"select-box", id:"item-prefecture"}) %>
        <%# <div class="weight-bold-text">
          発送までの日数
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:days_ship_id, DaysShip.all, :id, :name, {}, {class:"select-box", id:"item-scheduled-delivery"}) %>
      <%# </div>
    </div> %>
    <%# /配送について %>

    <%# 販売価格 %>
    <%# <div class="sell-price">
      <div class="weight-bold-text question-text">
        <span>販売価格<br>(¥300〜9,999,999)</span>
        <a class="question" href="#">?</a>
      </div>
      <div>
        <div class="price-content">
          <div class="price-text">
            <span>価格</span>
            <span class="indispensable">必須</span>
          </div>
          <span class="sell-yen">¥</span>
          <%= f.text_field :price, class:"price-input", id:"item-price", placeholder:"例）300" %>
        <%# </div>
        <div class="price-content">
          <span>販売手数料 (10%)</span>
          <span>
            <span id='add-tax-price'></span>円
          </span>
        </div>
        <div class="price-content">
          <span>販売利益</span>
          <span>
            <span id='profit'></span>円
          </span>
        </div>
      </div>
    </div> %>
    <%# /販売価格 %>

    <%# 注意書き %>
    <%# <div class="caution">
      <p class="sentence">
        <a href="#">禁止されている出品、</a>
        <a href="#">行為</a>
        を必ずご確認ください。
      </p>
      <p class="sentence">
        またブランド品でシリアルナンバー等がある場合はご記載ください。
        <a href="#">偽ブランドの販売</a>
        は犯罪であり処罰される可能性があります。
      </p>
      <p class="sentence">
        また、出品をもちまして
        <a href="#">加盟店規約</a>
        に同意したことになります。
      </p>
    </div> %>
    <%# /注意書き %>
    <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%= f.submit "変更する" ,class:"sell-btn" %>
      <%=link_to 'もどる', book_path, class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>

  <%# <footer class="items-sell-footer">
    <ul class="menu">
      <li><a href="#">プライバシーポリシー</a></li>
      <li><a href="#">フリマ利用規約</a></li>
      <li><a href="#">特定商取引に関する表記</a></li>
    </ul>
    <%= link_to image_tag('furima-logo-color.png' , size: '185x50'), "/" %>
    <%# <p class="inc">
      ©︎Furima,Inc.
    </p>
  </footer> %>
</div>

app/views/books/index.html.erb
<%= render "shared/header" %>

<%# jquery-3.0.0.min.jsというCDNから読み込むために必要な記述  %>
<script src="https://code.jquery.com/jquery-3.0.0.min.js"></script>
<script>
  $(function() {
  });
</script>

<%# jQuery.BgSwitcherに必要な記述 %>

<%# <div class="bg-slider">
 <h1 class="bg-slider__title">DEMO PAGE</h1>
</div> %>

  <%# 画面上部の帯部分 %>
  <div class='title-contents'>

    <h2 class='service-title'>
     Let's Meet The Best 
    </h2>
    
    <p class='service-explain'>
      みんなで最高の図書館をつくっていこう
    </p>
    <p class='service-explain'>
       おすすめの本を紹介するアプリです
    </p>
    <%# <div class='store-btn'>
      <%= link_to image_tag("https://linkmaker.itunes.apple.com/ja-jp/badge-lrg.svg?releaseDate=2011-09-21&kind=iossoftware&bubble=ios_apps", class:"apple-btn"), "#" %>
      <%# <%= link_to image_tag("dl-android.png", class:"google-btn"), "#" %>
    <%# </div> %>
  </div>
  <%# /画面上部の「人生を変えるフリマアプリ」帯部分  %>
  <div class="blank-space"></div>
  <div class="book-introduce"> 

    <div class="book-primary-items">
      <h3>このアプリはこんな人におすすめ<h3>
    </div>

    <strong>
    <div class="book-secondary-items">
    ・読書好きの友達とつながりたい！！
    </div>
    <div class="book-secondary-items">
    ・自分が読んだ本の学びをアウトプットしたい！！
    </div>
     <div class="book-secondary-items">
    ・誰でもいいからとにかく好きな本を紹介したい！
    </div></strong>

    <div class="book-primary-items">
      <h3>読書の効果について<h3>
    </div>
    
    <div class="book-tertiary-items">
      <h4><i class="fas fa-hand-point-right"></i>  脳の活性化！発想力が向上する。</h4><br>
      漢字や文法に詳しくなり、知識が増える。<br>
      本の内容を擬似体験したような状態になることで想像力が鍛えられる。
      </div>

    <div class="book-tertiary-items">
      <h5><i class="fas fa-hand-point-right"></i>  会話力や文章力が向上する。</h5><br>
      多方面から（客観的に）物事を考えられるようになり、相手の言葉が理解できるようになる。<br>
      言葉の表現などが豊かになり、人とのコミュニケーション力が養われる。<br>
    </div>
    
    <div class="book-tertiary-items">
      <h6><i class="fas fa-hand-point-right"></i>  ストレスの解消効果がある。</h6><br>
      6分の読書でストレスが68%も解消されたことが論文で証明されている。<br>
      うつ病の改善や寿命にまで好影響があることがわかっている。<br>
    </div>

    <div class="blank-space"></div>
    <div class="book-primary-items">
      <h3>読書を習慣化するためのコツについて<h3>
    </div>

    <div class="book-tertiary-items">
    <h4><i class="fas fa-hand-peace"></i> 自分の読みやすい本を見つける。</h4><br>
      自分に必要ない本、興味がないジャンルの本は読まない。<br>
      話題のベストセラーというだけの理由で選ばない。
    </div>

    <div class="book-tertiary-items">
    <h4><i class="fas fa-hand-peace"></i>  読書することに意気込まない。</h4><br>
      最初の１週間は毎日１分間だけでも読書することを目標にする。<br>
      習慣づけるために脳にこれは"毎日の行動であること"を理解させる。
    </div>

    <div class="blank-space"></div>

   <div class='book-contents'>
    <h2 class='title'>Posts List
    <span class="after">投稿一覧</span></h2>
    <%# <%= link_to '新規投稿一覧', "#", class: "subtitle" %>
    <ul class='book-lists'>

    <% @books.each do |book| %>
      <li class='list'>
      <p>
   
      <%= link_to "紹介者 #{book.user.nickname}", user_path(book.user.id),method: :get, class: :mypage %></p>
      <%# <p><a> 紹介者 </a><%= "#{book.user.nickname}"%></p>
          <%= link_to book_path(book) do %>
          <div class='item-img-content'>
           <%= image_tag book.image, class: "item-img" %>
            <div class='item-info'>
              <h3 class='item-name'>
                <p><a>著者 </a><%= "#{book.author}"%></p>
              </h3>
            </div>
          </div>
        <% end %>
      </li>
    <% end %>

    <%= link_to "/books/new", class: 'purchase-btn' do %>
      <span class='purchase-btn-text'>紹介する</span>
      <%= image_tag 'book-icon02.jpeg' , size: '185x50' ,class: "purchase-btn-icon" %>
    <% end %>

    <%= render "shared/footer" %>

app/views/books/new.html.erb
<div class="items-sell-contents">
  <header class="items-sell-header">
    <%= link_to image_tag('book-logo-color03.png' , size: '160x120'),root_path %>

  </header>
  <div class="items-sell-main">
    <h2 class="items-sell-title">あなたの好きな本を紹介してください</h2>
    <%= form_with model: @book, local: true do |f| %>    
    <%= render 'shared/error_messages', model: f.object %>

    <%# 商品名と商品説明 %>
    <div class="new-items">
      <div class="weight-bold-text">
        <%# 題名 %>
        <%# <span class="indispensable">必須</span> %>
      </div>
      <%= f.text_area :title, class:"items-text", id:"item-name", placeholder:"タイトル", maxlength:"40" %>

      <div class="weight-bold-text">
        <%# 著者 %>
        <%# <span class="indispensable">必須</span> %>
      </div>
      <%= f.text_area :author, class:"items-text", id:"item-name", placeholder:"著者", maxlength:"40" %>
      
      <div class="items-explain">
        <div class="weight-bold-text">
         <%# 要約 %>
          <%# <span class="indispensable">必須</span> %>
        </div>
        <%= f.text_area :summary, class:"items-text", id:"item-info", placeholder:"レビュー" ,rows:"7" ,maxlength:"1000" %>
      </div>
    </div>
    <%# /商品名と商品説明 %>

    <%# 商品の詳細 %>
    <div class="items-detail">
      <%# <div class="weight-bold-text">本の詳細</div> %>
      <div class="form">
        <div class="weight-bold-text">
          カテゴリー
          <%# <span class="indispensable">必須</span> %>
        </div>
        <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
        <div class="weight-bold-text">
          出版社
          <%# <span class="indispensable">必須</span> %>
        </div>
        <%= f.collection_select(:publishing_company_id, PublishingCompany.all, :id, :name, {}, {class:"select-box", id:"item-sales-status"}) %>
      </div>
    </div>
    <div class="items-explain">
        <div class="weight-bold-text">
          <%# 得られる学び %>
          <%# <span class="indispensable">任意</span> %>
        </div>
        <%= f.text_area :output, class:"items-text", id:"item-info", placeholder:"得られた学び" ,rows:"7" ,maxlength:"1000" %>
    </div>
    <%# /商品の詳細 %>

    <%# 配送について %>
    <%# <div class="items-detail">
      <div class="weight-bold-text question-text">
        <span>配送について</span>
        <a class="question" href="#">?</a>
      </div>
      <div class="form">
        <div class="weight-bold-text">
          配送料の負担
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:shipping_charge_id, ShippingCharge.all, :id, :name, {}, {class:"select-box", id:"item-shipping-fee-status"}) %>
        <%# <div class="weight-bold-text">
          発送元の地域
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:city_id, City.all, :id, :name, {}, {class:"select-box", id:"item-prefecture"}) %>
        <%# <div class="weight-bold-text">
          発送までの日数
          <span class="indispensable">必須</span>
        </div>
        <%# <%= f.collection_select(:days_ship_id, DaysShip.all, :id, :name, {}, {class:"select-box", id:"item-scheduled-delivery"}) %>
      <%# </div> %>
    <%# </div>  %>
    <%# /配送について %>

    <%# 販売価格 %>
    <%# <div class="sell-price">
      <div class="weight-bold-text question-text">
        <span>販売価格<br>(¥300〜9,999,999)</span>
        <a class="question" href="#">?</a>
      </div>
      <div>
        <div class="price-content">
          <div class="price-text">
            <span>価格</span>
            <span class="indispensable">必須</span>
          </div>
          <span class="sell-yen">¥</span>
          <%= f.text_field :price, class:"price-input", id:"item-price", placeholder:"半角数字で入力" %>
        <%# </div>
        <div class="price-content">
          <span>販売手数料 (10%)</span>
          <span>
            <span id='add-tax-price'></span>円
          </span>
        </div>
        <div class="price-content">
          <span>販売利益</span>
          <span>
            <span id='profit'></span>円
        </div>
        </span>
      </div>
    </div> %>
    <%# /販売価格 %>

    <%# 出品画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        本の画像
        <span class="indispensable"></span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"item-image" %>
      </div>
    </div>
    <%# /出品画像 %>

    <%# 注意書き %>
    <%# <div class="caution">
      <p class="sentence">
        <a href="#">禁止されている出品、</a>
        <a href="#">行為</a>
        を必ずご確認ください。
      </p>
      <p class="sentence">
        またブランド品でシリアルナンバー等がある場合はご記載ください。
        <a href="#">偽ブランドの販売</a>
        は犯罪であり処罰される可能性があります。
      </p>
      <p class="sentence">
        また、出品をもちまして
        <a href="#">加盟店規約</a>
        に同意したことになります。
      </p>
    </div> %>
    <%# /注意書き %>
    <%# 下部ボタン %>
    <div class="sell-btn-contents">
   
      <%= f.submit "紹介する" ,class:"sell-btn" %>
      <%=link_to '戻る', root_path, class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  
  <% end %>

  <%# <footer class="items-sell-footer">
    <ul class="menu">
      <li><a href="#">PRIVACY POLICY</a></li>
      <li><a href="#">OurLiv 利用規約</a></li>
      <li><a href="#">特定商取引に関する表記</a></li>
    </ul>
    <%= link_to image_tag('furima-logo-color.png' , size: '185x50'), "/" %>
    <%# <p class="inc"> %>
      <%# ©︎OurLib,Inc.
    </p>
  </footer> %>
</div>

app/views/books/show.html.erb
<%= render "shared/header" %>

<%# 商品の概要 %>
<div class="item-show">

  <div class="item-box">
    <h2 class="name">
      <%= @book.title %>
    </h2>

    <div class="item-img-content">
      <%= image_tag @book.image ,class:"item-box-img" %>
    </div>

    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-item">紹介者</th>
          <td class="detail-value"><%= @book.user.nickname %></td>
        </tr>

        <tr>
          <th class="detail-item">レビュー</th>
          <td class="detail-value"><%= @book.summary %></td>
        </tr>

        <tr>
          <th class="detail-item">カテゴリー</th>
          <td class="detail-value"><%= @book.category.name %></td>
        </tr>

        <tr>
          <th class="detail-item">出版社</th>
          <td class="detail-value"><%= @book.publishing_company.name %></td>
        </tr>

        <tr>
          <th class="detail-item">得られた学び</th>
          <td class="detail-value"><%= @book.output %></td>
        </tr>
      </tbody>
    </table>

    <div class="book-select">
      <% if user_signed_in? %>
        <% if current_user.id  == @book.user_id %>
          <div class = "item-red-btn">
             <i class="fas fa-pencil-alt fa-1x "></i>
             <%= link_to "Edit", edit_book_path(@book.id), class: "item-red-btn" %>
          </div>

          <div class="item-destroy">
            <i class="fas fa-trash fa-1x"></i>
            <%= link_to "Delete", book_path(@book.id), method: :delete, class:"item-destroy" %>
          </div>
        <% else %>
        <%# <%= link_to "購入画面に進む", item_purchase_records_path(book_id: @book.id), class:"item-red-btn"%>
       <% end %>
            <% end %>
    </div>

      <div class="option">
        <div class="favorite-btn">
          <%= image_tag "star.png" ,class:"favorite-star-icon" ,width:"20",height:"20"%>
          <span>貸してね 0</span>
        </div>
      
        <div class="report-btn">
          <%= image_tag "flag.png" ,class:"report-flag-icon" ,width:"20",height:"20"%>
          <span>不適切な内容の通報</span>
        </div>
      </div>
  </div>
  <%# /商品の概要 %>

  <div class="comment-box">
    <form>
      <textarea class="comment-text"></textarea>
      <p class="comment-warn">
        相手のことを考え丁寧なコメントを心がけましょう。
        <br>
        不快な言葉遣いなどは利用制限や退会処分となることがあります。
      </p>
      <button type="submit" class="comment-btn">
        <%= image_tag "comment.png" ,class:"comment-flag-icon" ,width:"20",height:"25"%>
        <span>コメントする<span>
      </button>
    </form>
  </div>
  <div class="links">
    <a href="#" class="change-item-btn">
      <<
    </a>
    <a href="#" class="change-item-btn">
      >>
    </a>
  </div>
  <a href="#" class="another-item"><%= @book.category.name %>をもっと見る</a>
</div>

<%= render "shared/footer" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>OurLib</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%# Font Awesomeを使用するためのコード %>
  <script src="https://kit.fontawesome.com/47deb5100b.js" crossorigin="anonymous"></script>
  <script defer src="https://use.fontawesome.com/releases/v5.15.3/js/all.js"></script>

  <%#デフォルトの記述 %>
  <%# <script type="text/javascript" src="https://js.pay.jp/v1/"></script>
  <%= stylesheet_link_tag 'application', media: 'all'%>
  <%# <%= javascript_pack_tag 'application' %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%# 上記の記述でwebpackで管理されているJavaScriptを参照している %>

</head>

<body>
  <%= yield %>
  <%# Font Awesomeを使用するためのコード %>
  <!-- Ready to use Font Awesome. Activate interlock. Dynotherms - connected. Infracells - up. Icons are go! -->
</body>

</html>

app/views/layouts/bapplication.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Books13171</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_second-header.html.erb
<header class='second-header'>
  <%= link_to image_tag("furima-logo-color.png", class:"second-logo"), "/" %>
</header>